version: 4.0.0
variant: default
logo: 'https://img1.imgtp.com/2022/07/06/8CWtxPzp.png'
head:
    favicon: 'https://img1.imgtp.com/2022/07/06/8CWtxPzp.png'
    canonical_url:
    open_graph:
        title: QYJS
        type: blog
        url: 'https://qyjs.github.io/'
        image: 'https://img1.imgtp.com/2022/07/06/8CWtxPzp.png'
        site_name: FlyingFishSauce
        author: QYJS
        description: demo
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: FlyingFishSauce
        description: DEMO
        url: 'https://qyjs.github.io/'
        author: qyjs
        image: 'https://cdn.jsdelivr.net/gh/removeif/removeif.github.io@latest/img/avatar.jpg'
    meta:
        - ''
    rss: /atom.xml
navbar:
    menu:
        首页: /
        归档: /archives
        分类: /categories
        标签: /tags
        音乐: /music
        影音: /media
        相册: /album
        友链: /friend
        碎碎念: /self-talking
        留言: /message
        关于: /about
    links:
        Join Gitter:
            icon: fab fa-gitter
            url: 'https://gitter.im/hexo-theme-amazing/community'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/removeif/hexo-theme-amazing'
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/removeif/hexo-theme-amazing'
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: 'https://creativecommons.org/licenses/by-nc/4.0/'
search:
    type: insight
donates:
    -
        type: alipay
        qrcode: 'https://raw.githubusercontent.com/removeif/blog_image/master/img/2019/20190802135456.png'
    -
        type: wechat
        qrcode: 'https://raw.githubusercontent.com/removeif/blog_image/master/img/2019/20190802135550.png'
share:
    type: sharejs
    install_url: ''
sidebar:
    left:
        sticky: true
    right:
        sticky: false
widgets:
    -
        position: left
        type: toc
        index: false
    -
        position: left
        type: profile
        author: FlyingFishSauce
        author_title: QYJS
        location: China
        avatar: 'https://img1.imgtp.com/2022/07/06/8CWtxPzp.png'
        avatar_rounded: true
        gravatar: 
        follow_link: 'https://github.com/qyjs'
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/qyjs'
            Weibo:
                icon: fab fa-weibo
                url: 'https://weibo.com/qyjs'
            Email:
                icon: fa fa-envelope
                url: 'mailto:qyjs@163.com'
            Next:
                icon: fab fa-dribbble
                url: 'https://qyjs.github.io'
            RSS:
                icon: fas fa-rss
                url: /atom.xml
        has_hitokoto: true
    -
        position: right
        type: latest_comment
    -
        position: left
        type: links
        links:
            Hexo: 'https://hexo.io'
            Bulma: 'https://bulma.io'
    -
        position: right
        type: latest_comment
    -
        position: right
        type: recent_posts
    -
        position: right
        type: categories
    -
        position: right
        type: archives
    -
        position: right
        type: tags
    -
        position: right
        type: subscribe_email
        description: 
        feedburner_id: ''
    -
        position: right
        type: adsense
adsense_client_id: 
adsense_slot_id: '5134765588'
article_head_has_ad: true
comment_head_has_ad: true
index_zero_position_ad: true
index_ad_positions: '2,5,9'
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 7c84655c016d9786043134d1d7dacd61
    busuanzi: true
    cnzz:
        id: 
        web_id: 
    gallery: true
    google_analytics:
        tracking_id: G-982D4W4JS6
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
providers:
    cdn: loli
    fontcdn: loli
    iconcdn: loli
footer_copyright_dsec: '© 版权说明：[本网站所有内容均收集于互联网或自己创作,<br />&nbsp;&nbsp;&nbsp;&nbsp;方便于网友与自己学习交流，如有侵权，请<a href="/message" target="_blank">留言</a>，立即处理]<br />'
website_start_time: '2018/11/11 00:00:00'
footer_registered_no: 川ICP备88888888号-8（测试）
side_music_netease_id: 2364053447
busuanzi_only_count: false
has_live_2D_switch: true
use_pjax: true
